# Generated by Django 5.2.10 on 2026-03-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
